### ISSUE TITLE
After compose up: Host is unreachable "http://credit-agency:9002/person-rating/feed"

### ISSUE THREAD

**Issue by clojj** [mploed/ddd-with-spring#18]
After fixing this issue locallly (by renaming the artifact in the Dockerfile)
https://github.com/mploed/ddd-with-spring/issues/16

... I get this error after running
`docker-compose up --build`

```
ddd-with-spring-scoring | 2021-02-12 20:23:27.310  WARN 1 --- [ask-scheduler-1] .c.j.MappingJackson2HttpMessageConverter : Failed to evaluate Jackson deserialization for type [[simple type, class com.rometools.rome.feed.atom.Feed]]: com.fasterxml.jackson.databind.JsonMappingException: Conflicting setter definitions for property "content": org.jdom2.Element#setContent(1 params) vs org.jdom2.Element#setContent(1 params)
ddd-with-spring-scoring | 2021-02-12 20:23:28.347 ERROR 1 --- [ask-scheduler-1] o.s.integration.handler.LoggingHandler   : org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://credit-agency:9002/person-rating/feed": Host is unreachable (Host unreachable); nested exception is java.net.NoRouteToHostException: Host is unreachable (Host unreachable)
ddd-with-spring-scoring |       at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:743)
ddd-with-spring-scoring |       at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:686)
ddd-with-spring-scoring |       at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:602)
ddd-with-spring-scoring |       at com.mploed.dddwithspring.scoring.feeds.CreditAgencyPoller.poll(CreditAgencyPoller.java:53)
ddd-with-spring-scoring |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

..should "http://credit-agency:9002" be available in the docker network ?

**Comment by ljluestc** [comment]
Step 1: Verify Docker Network Configuration
Ensure that all services are part of the same Docker network. By default, Docker Compose creates a network for all services defined in the docker-compose.yml file. Verify that the credit-agency service is correctly defined and reachable.

Example docker-compose.yml:

```
version: '3.8'
services:
  credit-agency:
    image: credit-agency:latest
    ports:
      - "9002:9002"
    networks:
      - my-network

  ddd-with-spring-scoring:
    image: ddd-with-spring-scoring:latest
    depends_on:
      - credit-agency
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
```

Step 2: Check Service Availability
Ensure that the credit-agency service is running and listening on port 9002. You can verify this by:

Logs: Check the logs of the credit-agency service to ensure it started successfully:

```
docker-compose logs credit-agency
```

Shell Access: Access the container and check if the service is running:

```
docker-compose exec credit-agency sh
curl http://localhost:9002/person-rating/feed
```

Step 3: Verify DNS Resolution
Ensure that the credit-agency hostname resolves correctly within the ddd-with-spring-scoring container. You can test this by:

Accessing the ddd-with-spring-scoring container:

```
docker-compose exec ddd-with-spring-scoring sh
```

Running a DNS lookup:

```
nslookup credit-agency
```

Testing connectivity:

```
curl http://credit-agency:9002/person-rating/feed
```

Step 4: Add Retry Logic
If the credit-agency service takes time to start, the ddd-with-spring-scoring service might fail to connect initially. Add retry logic in your application to handle temporary unreachability.

Example (Java/Spring):

```
import org.springframework.retry.annotation.Backoff;
import org.springframework.retry.annotation.Retryable;
import org.springframework.web.client.RestTemplate;

public class CreditAgencyPoller {

    private final RestTemplate restTemplate;

    public CreditAgencyPoller(RestTemplate restTemplate) {
        this.restTemplate = restTemplate;
    }

    @Retryable(
        value = {ResourceAccessException.class},
        maxAttempts = 5,
        backoff = @Backoff(delay = 1000)
    )
    public void poll() {
        String url = "http://credit-agency:9002/person-rating/feed";
        restTemplate.exchange(url, HttpMethod.GET, null, Feed.class);
    }
}
```

Step 5: Debugging Tips
Check Docker Network:

```
docker network inspect <network_name>
```

Replace <network_name> with the name of the network used in your docker-compose.yml.

Inspect Containers:

```
docker-compose ps
docker inspect <container_id>
```

Increase Logging: Add logging to your application to capture more details about the connection attempt.
